// Auto-generated by cmake

#ifndef HIP_VERSION_H
#define HIP_VERSION_H

#define HIP_VERSION_MAJOR 4
#define HIP_VERSION_MINOR 2
#define HIP_VERSION_PATCH 21155
#define HIP_VERSION       (HIP_VERSION_MAJOR * 100 + HIP_VERSION_MINOR)

#define __HIP_HAS_GET_PCH 1

#endif

